# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - develop
    - release/*

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreCLI@2
    displayName: 'Install Cake'
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'restore'


- task: DotNetCoreCLI@2
    displayName: 'Run Cake Build Script'
    inputs:
      command: 'custom'
      custom: 'cake'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: 'stage/TestResult.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    failTaskOnFailedTests: true # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional  
